### PR TITLE
Update list.yaml

### PR DESCRIPTION
**Pull request by WhiteAbeLincoln**
Adds base16-brushtrees-scheme

### CODE REVIEW

**Comment by chriskempson** [comment]
Just noticed that this fails to parse on PHP builder because the comment directly follows a character. e.g. `
base00: "E3EFEF"#E3EFEF` instead of `base00: "E3EFEF" #E3EFEF` I wonder if this might trip up other YAML parsers too? Might be best to put a space in just in case.

**Comment by chriskempson** [comment]
Also just noticed that both scheme have the same name and so are overwritten.

**Comment by belak** [comment]
The same name in the scheme file is fine because the slug comes from the file name. That was what 0.8.1 of the spec changed, I believe. The PHP builder only supports 0.8.0 which slugifies the scheme name and uses that for the slug.

**Comment by belak** [comment]
Looking at the comments, it looks like that's not compliant with the yaml spec, so it would be good to get that changed. The spec specifies that "Comments must be separated from other tokens by white space characters." http://yaml.org/spec/1.2/spec.html#id2780069

**Comment by WhiteAbeLincoln** [comment]
Done. I had them in there so that I could highlight the colors with emacs while testing, and forgot to remove them

**Comment by belak** [comment]
Ah, yep. The one downside to not requiring `#` symbols is that rainbow-mode doesn't handle it properly. Anyway, the emacs themes are generated and pushed, so they'll show up in melpa with the next build.

**Comment by belak** [comment]
Also, in the future, it's pretty easy to test out colors if you use something like [this](https://github.com/belak/base16-emacs#development). Then you can just add a new scheme file and test that out without having to generate every time. :)

**Comment by WhiteAbeLincoln** [comment]
Thanks! That's good advice for the future. I think I was using that, since I actually have a [script](https://github.com/WhiteAbeLincoln/themer/) which automatically builds a custom colorscheme for emacs among other things. 

Unfortunately, I can't figure out how to get emacs to re-source the theme file after it's been modified in place. Terminal vim just works, and I can send a message to nvim to tell it to reload, but emacs has been difficult. Do you have any suggestions?

**Comment by belak** [comment]
Unfortunately, I don't. I usually try to keep a few instances of emacs open... one for previewing and one for editing.

I originally designed the template so it could be called with a different alist and it would update the theme colors, but that doesn't appear to be working quite right.

**Pull request merged**
