### PR TITLE
add tender color scheme

### PR DESCRIPTION
**Pull request by DanManN**
based on tender.vim https://github.com/jacoborus/tender.vim

### CODE REVIEW

**Comment by devhell** [comment]
I love the 'Tender' color scheme and so I'm wondering if this has not been merged for a reason?

**Comment by Misterio77** [comment]
@devhell, the maintainers seem to be a a bit inactive the last year or so, definitively a bottleneck in the project lately.
https://github.com/chriskempson/base16/issues/74

**Comment by belak** [comment]
Yeah, I haven't been very active lately- I'm happy to merge themes while I renew the push in the issue you mentioned. Thanks for the reminder.

**Comment by Misterio77** [comment]
Sorry if i came off as rude. Thanks for all the work in the project

**Comment by devhell** [comment]
Awesome, thank you both so much! 👍

**Pull request merged**
