### PR TITLE
Add framer scheme

### PR DESCRIPTION
**Pull request by jssee**

### CODE REVIEW

**Comment by belak** [comment]
Thanks for submitting this! In order to get this scheme to comply with the spec (and work with builders), you should remove the `#` sign from the colors in the scheme yaml.

**Comment by jssee** [comment]
@belak thanks for mentioning it, I have updated the scheme, should be good now 👍

**Comment by reyemxela** [comment]
@jssee, I was just about to merge this, but I noticed that your repo name is "base-16-framer-scheme" with the extra dash in "base-16". I'm honestly not sure how big of a deal the naming convention is? It'd be easy enough to rename the repo either way though, and would help with consistency. If you want to rename it and update the url in the PR, I'll merge it.

Nice colorscheme btw!

**Comment by jssee** [comment]
@reyemxela good eye, updated it now!

**Comment by reyemxela** [comment]
I merged it here, and also added it to the schemes section of the [base16](https://github.com/chriskempson/base16) readme file.

**Pull request merged**
