### PR TITLE
Add Sig scheme

### PR DESCRIPTION
**Pull request by sorenbug**
For some reason builders won't let me supply a theme on my local machine so I think this is the only way to do it.

### CODE REVIEW

**Comment by belak** [comment]
It looks like this might be a private repo?

**Comment by belak** [comment]
It doesn't look like this scheme exists any more?

**Comment by sorenbug** [comment]
Yeah. I don't actually use the theme and I figure if I ever need to I'll just write my own quick command line thing for builders.

**Comment by belak** [comment]
Fair enough, thanks for following up!

**Pull request closed without merging**
